# Generated by Django 5.2.6 on 2025-09-10 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('appid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('apiname', models.CharField(max_length=200)),
                ('displayname', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('icon', models.URLField(blank=True)),
                ('icongray', models.URLField(blank=True)),
            ],
            options={
                'unique_together': {('appid', 'apiname')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steamid64', models.CharField(max_length=32, unique=True)),
                ('persona', models.CharField(blank=True, max_length=100)),
                ('avatar', models.URLField(blank=True)),
                ('level', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appid', models.IntegerField()),
                ('apiname', models.CharField(max_length=200)),
                ('achieved', models.BooleanField(default=False)),
                ('unlocktime', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.profile')),
            ],
            options={
                'unique_together': {('profile', 'appid', 'apiname')},
            },
        ),
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playtime_forever', models.IntegerField(default=0)),
                ('playtime_2weeks', models.IntegerField(default=0)),
                ('rtime_last_played', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.game')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.profile')),
            ],
            options={
                'unique_together': {('profile', 'game')},
            },
        ),
    ]
